// @generated by mad-hatter-guardian scaffold
// concept-map checksum: 3a2a238ba3311efd
// DO NOT EDIT — regenerate with: cargo run -p mad-hatter-guardian --bin scaffold

use mad_hatter::{ConceptMapToken, FatalToken, SuppressibleToken, Transaction};

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CheckUserAccessFatal {
    DbInsertUser,
    DbQuery,
}

impl FatalToken for CheckUserAccessFatal {}

impl ConceptMapToken for CheckUserAccessFatal {
    fn operation_name(&self) -> &'static str {
        match self {
            Self::DbInsertUser => "CheckUserAccess::db_insert_user",
            Self::DbQuery => "CheckUserAccess::db_query",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CheckUserAccessSuppressible {}

impl SuppressibleToken for CheckUserAccessSuppressible {}

impl ConceptMapToken for CheckUserAccessSuppressible {
    fn operation_name(&self) -> &'static str {
        match *self {}
    }
}

pub struct CheckUserAccess;

impl Transaction for CheckUserAccess {
    type Fatal = CheckUserAccessFatal;
    type Suppressible = CheckUserAccessSuppressible;
    fn name() -> &'static str { "CheckUserAccess" }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ProcessOrdersFatal {
    ReadOrders,
    ParseOrders,
    WriteSummary,
}

impl FatalToken for ProcessOrdersFatal {}

impl ConceptMapToken for ProcessOrdersFatal {
    fn operation_name(&self) -> &'static str {
        match self {
            Self::ReadOrders => "ProcessOrders::read_orders",
            Self::ParseOrders => "ProcessOrders::parse_orders",
            Self::WriteSummary => "ProcessOrders::write_summary",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ProcessOrdersSuppressible {
    ProcessSingle,
    Notify,
    Cleanup,
}

impl SuppressibleToken for ProcessOrdersSuppressible {}

impl ConceptMapToken for ProcessOrdersSuppressible {
    fn operation_name(&self) -> &'static str {
        match self {
            Self::ProcessSingle => "ProcessOrders::process_single",
            Self::Notify => "ProcessOrders::notify",
            Self::Cleanup => "ProcessOrders::cleanup",
        }
    }
}

pub struct ProcessOrders;

impl Transaction for ProcessOrders {
    type Fatal = ProcessOrdersFatal;
    type Suppressible = ProcessOrdersSuppressible;
    fn name() -> &'static str { "ProcessOrders" }
}
